force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/DSD_Data_Skew_Detector_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Data Skew Detector Settings</label>
    <pluralLabel>Data Skew Detector Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Report_Other_Record_Counts__c.field-meta.xml
<CustomField>
    <fullName>DSD_Report_Other_Record_Counts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, record counts of child records will be recorded based on the Reportng Threshold value.</description>
    <inlineHelpText>When checked, record counts of child records will be recorded based on the Reportng Threshold value.</inlineHelpText>
    <label>Report Other Record Counts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Reporting_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Reporting_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</inlineHelpText>
    <label>Reporting Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Skew_Type__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Type__c</fullName>
    <description>The type of data skew to detect</description>
    <inlineHelpText>The type of data skew to detect</inlineHelpText>
    <label>Skew Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSD_Settings.cls
public with sharing class DSD_Settings {

    public static DSD_Data_Skew_Detector_Settings__mdt testAccountSettings;
    private static DSD_Data_Skew_Detector_Settings__mdt accountSettings;

    public static DSD_Data_Skew_Detector_Settings__mdt getAccountSettings() {

        if(accountSettings != null) return accountSettings;

        if(Test.isRunningTest() && testAccountSettings != null) {
            accountSettings = testAccountSettings;
            return accountSettings;
        }

        accountSettings = getSingleRecord('DSD_Account_Settings');
        return accountSettings;
    }

    private static DSD_Data_Skew_Detector_Settings__mdt getSingleRecord(String apiName) {
        return [SELECT MasterLabel,
            QualifiedApiName,
            DSD_Skew_Type__c, 
            DSD_Skew_Threshold__c, 
            DSD_Report_Other_Record_Counts__c, 
            DSD_Reporting_Threshold__c 
            FROM DSD_Data_Skew_Detector_Settings__mdt 
            WHERE QualifiedApiName = :apiName];
    }
}