force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/DSD_Data_Skew_Detector_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Data Skew Detector Settings</label>
    <pluralLabel>Data Skew Detector Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Child_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Child_Object_API_Name__c</fullName>
    <description>The API name of the child object to look for data skew on</description>
    <inlineHelpText>The API name of the child object to look for data skew on</inlineHelpText>
    <label>Child Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Parent_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Parent_Object_API_Name__c</fullName>
    <description>The API name of the parent object to look for data skew on</description>
    <inlineHelpText>The API name of the parent object to look for data skew on</inlineHelpText>
    <label>Parent Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Reporting_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Reporting_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</inlineHelpText>
    <label>Reporting Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Skew_Type__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Type__c</fullName>
    <description>The type of data skew to detect</description>
    <inlineHelpText>The type of data skew to detect</inlineHelpText>
    <label>Skew Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/DSD_Data_Skew_Result__c.object-meta.xml
<CustomObject>
    <description>Stores results of Data Skew Detector</description>
    <label>Data Skew Result</label>
    <nameField>
        <displayFormat>DSR-{0000}</displayFormat>
        <label>Data Skew Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Skew Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Child_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Child_Object_API_Name__c</fullName>
    <description>The API name of the object that has too many records that lookup to the parent object</description>
    <inlineHelpText>The API name of the object that has too many records that lookup to the parent object</inlineHelpText>
    <label>Child Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Parent_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Parent_Object_API_Name__c</fullName>
    <description>The API name of the object that has data skew due to too many records looking up to it</description>
    <inlineHelpText>The API name of the object that has data skew due to too many records looking up to it</inlineHelpText>
    <label>Parent Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Reporting_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Reporting_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</inlineHelpText>
    <label>Reporting Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skew_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Record_Count__c</fullName>
    <description>The number of records found to that meet the data skew threshold</description>
    <inlineHelpText>The number of records found to that meet the data skew threshold</inlineHelpText>
    <label>Skew Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skew_Type__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Type__c</fullName>
    <description>Possible values: Account</description>
    <inlineHelpText>Possible values: Account</inlineHelpText>
    <label>Skew Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skewed_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skewed_Record_ID__c</fullName>
    <description>The record id of the record that has data skew</description>
    <inlineHelpText>The record id of the record that has data skew</inlineHelpText>
    <label>Skewed Record ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSD_ResultsSupport.cls
public inherited sharing class DSD_ResultsSupport {
    
    @TestVisible public static final String SKEW_TYPE_ACCOUNT = 'Account';
    @TestVisible public static final String SKEW_TYPE_OWNER = 'Owner';

    public static List<DSD_Data_Skew_Result__c> saveResults(DSD_Data_Skew_Detector_Settings__mdt settings, Map<Id, Integer> parentChildRecCountMap) {
        hardDeleteResults(settings.DSD_Skew_Type__c);
        DSD_Data_Skew_Result__c[] results = new DSD_Data_Skew_Result__c[]{};
        
        for(Id recId : parentChildRecCountMap.keySet()) {
            results.add(new DSD_Data_Skew_Result__c(
                DSD_Child_Object_API_Name__c = settings.DSD_Child_Object_API_Name__c,
                DSD_Parent_Object_API_Name__c = settings.DSD_Parent_Object_API_Name__c,
                DSD_Reporting_Threshold__c = settings.DSD_Reporting_Threshold__c,
                DSD_Skew_Record_Count__c = parentChildRecCountMap.get(recId),
                DSD_Skew_Threshold__c = settings.DSD_Skew_Threshold__c,
                DSD_Skew_Type__c = settings.DSD_Skew_Type__c,
                DSD_Skewed_Record_ID__c = recId
            ));
        }

        insert results;
        return results;
    }

    public static void hardDeleteResults(String skewType) {
        Database.DeleteResult[] results = Database.delete([SELECT Id FROM DSD_Data_Skew_Result__c WHERE DSD_Skew_Type__c = :skewType LIMIT 50000], false);

        DSD_UtilityFunctions.hardDeleteObjects(results);
    }

    @TestVisible 
    public static List<DSD_Data_Skew_Result__c> getAllResults() {
        return getResultsByType(null);
    }

    @TestVisible
    public static List<DSD_Data_Skew_Result__c> getResultsByType(String skewType) {
        String query = 'SELECT DSD_Child_Object_API_Name__c, DSD_Parent_Object_API_Name__c, DSD_Reporting_Threshold__c, DSD_Skew_Record_Count__c, DSD_Skew_Threshold__c, DSD_Skew_Type__c, DSD_Skewed_Record_ID__c FROM DSD_Data_Skew_Result__c';

        if(skewType != '' && skewType != null) query += ' WHERE DSD_Skew_Type__c = :skewType';

        return Database.query(query);
    }
}