force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/DSD_Data_Skew_Detector_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Data Skew Detector Settings</label>
    <pluralLabel>Data Skew Detector Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Report_Other_Record_Counts__c.field-meta.xml
<CustomField>
    <fullName>DSD_Report_Other_Record_Counts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, record counts of child records will be recorded based on the Reportng Threshold value.</description>
    <inlineHelpText>When checked, record counts of child records will be recorded based on the Reportng Threshold value.</inlineHelpText>
    <label>Report Other Record Counts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Reporting_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Reporting_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</inlineHelpText>
    <label>Reporting Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DSD_AccountDataSkewBatch.cls
public without sharing class DSD_AccountDataSkewBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    // vars that maintain initial state 
    private final String query;
    private final DSD_Data_Skew_Detector_Settings__mdt accountSettings;

    // vars that maintain state across batches
    private Map<Id, Integer> accountContactCount;

    public DSD_AccountDataSkewBatch() {
        this.accountSettings = DSD_Settings.getAccountSkewSettings();
        this.accountContactCount = new Map<Id, Integer>();
        this.query = 'SELECT Id FROM Account';
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {

        // declare vars for use within the loop
        Id accountId;
        Integer contactCount;

        for (AggregateResult ar : [SELECT COUNT(Id) ContactCount, AccountId FROM Contact WHERE AccountId in :scope GROUP BY AccountId]) {
            
            accountId = (Id)ar.get('AccountId');
            contactCount = (Integer)ar.get('ContactCount');

            if(contactCount >= accountSettings.DSD_Skew_Threshold__c) {
                accountContactCount.put(accountId, contactCount);
            }
            else if(accountSettings.DSD_Report_Other_Record_Counts__c) {
                if(contactCount >= accountSettings.DSD_Reporting_Threshold__c) {
                    accountContactCount.put(accountId, contactCount);
                }
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
        DSD_ResultsSupport.hardDeleteResults(DSD_ResultsSupport.SKEW_TYPE_ACCOUNT);
        DSD_ResultsSupport.saveResults(accountSettings, accountContactCount);
    }
}