force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/DSD_Data_Skew_Detector_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Data Skew Detector Settings</label>
    <pluralLabel>Data Skew Detector Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Detector_Settings__mdt/fields/DSD_Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/DSD_Data_Skew_Result__c.object-meta.xml
<CustomObject>
    <description>Stores results of Data Skew Detector</description>
    <label>Data Skew Result</label>
    <nameField>
        <displayFormat>DSR-{0000}</displayFormat>
        <label>Data Skew Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Skew Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Child_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Child_Object_Name__c</fullName>
    <description>The API name of the object that has too many records that lookup to the parent object</description>
    <inlineHelpText>The API name of the object that has too many records that lookup to the parent object</inlineHelpText>
    <label>Skewed Child Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Parent_Object_Name__c</fullName>
    <description>The API name of the object that has data skew due to too many records looking up to it</description>
    <inlineHelpText>The API name of the object that has data skew due to too many records looking up to it</inlineHelpText>
    <label>Skewed Parent Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skew_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Record_Count__c</fullName>
    <description>The number of records found to that meet the data skew threshold</description>
    <inlineHelpText>The number of records found to that meet the data skew threshold</inlineHelpText>
    <label>Skew Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skewed_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skewed_Record_ID__c</fullName>
    <description>The record id of the record that has data skew</description>
    <inlineHelpText>The record id of the record that has data skew</inlineHelpText>
    <label>Skewed Record ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSD_TestAccountDataSkewBatch.cls
@isTest
public with sharing class DSD_TestAccountDataSkewBatch {
    
    @isTest
    static void TestAccountsWithAndWithoutSkew(){
        
        Integer skewThresholdForTest = 10;

        List<Account> acctsWithSkew = DSD_TestDataFactory.GetTestAccounts('skewedacct', 10);
        insert acctsWithSkew;
        Map<Id, Account> acctsWithSkewMap = new Map<Id, Account>(acctsWithSkew);

        List<Contact> contacts = DSD_TestDataFactory.AddContactsToAccounts(acctsWithSkew, 10);
        insert contacts;

        List<Account> acctsWithoutSkew = DSD_TestDataFactory.GetTestAccounts('noskewacct', 1);
        insert acctsWithoutSkew;
        Map<Id, Account> acctsWithoutSkewMap = new Map<Id, Account>(acctsWithoutSkew);

        List<Contact> contacts2 = DSD_TestDataFactory.AddContactsToAccounts(acctsWithoutSkew, 9);
        insert contacts2;

        Test.startTest();

        DSD_Data_Skew_Detector_Settings__mdt settings = DSD_Settings.getAccountSettings();
        settings.DSD_Skew_Threshold__c = skewThresholdForTest;
        DSD_Settings.testAccountSettings = settings;

        Database.executeBatch(new DSD_AccountDataSkewBatch());
        
        Test.stopTest();

        DSD_Data_Skew_Result__c[] results = DSD_ResultsSupport.getResultsByType(DSD_ResultsSupport.SKEW_TYPE_ACCOUNT);
        System.assertEquals(10, results.size());
        
        for(DSD_Data_Skew_Result__c r : results) {
            System.assert(acctsWithSkewMap.containsKey(r.DSD_Skewed_Record_ID__c));
            System.assertEquals(10, r.DSD_Skew_Record_Count__c, 'Skew record count should be 10 but is not');
            System.assertEquals('Account', r.DSD_Parent_Object_Name__c, 'Parent object should be Account but is not');
            System.assertEquals('Contact', r.DSD_Child_Object_Name__c, 'Child object should be Contact but is not');
            System.assertEquals(false, acctsWithoutSkewMap.containsKey(r.DSD_Skewed_Record_ID__c), 'An account without skew was flagged as having skew');
        }
    }
}