force-app/main/default/objects/DSD_Data_Skew_Result__c/DSD_Data_Skew_Result__c.object-meta.xml
<CustomObject>
    <description>Stores results of Data Skew Detector</description>
    <label>Data Skew Result</label>
    <nameField>
        <displayFormat>DSR-{0000}</displayFormat>
        <label>Data Skew Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Skew Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Child_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Child_Object_API_Name__c</fullName>
    <description>The API name of the object that has too many records that lookup to the parent object</description>
    <inlineHelpText>The API name of the object that has too many records that lookup to the parent object</inlineHelpText>
    <label>Child Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Parent_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DSD_Parent_Object_API_Name__c</fullName>
    <description>The API name of the object that has data skew due to too many records looking up to it</description>
    <inlineHelpText>The API name of the object that has data skew due to too many records looking up to it</inlineHelpText>
    <label>Parent Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skew_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skew_Record_Count__c</fullName>
    <description>The number of records found to that meet the data skew threshold</description>
    <inlineHelpText>The number of records found to that meet the data skew threshold</inlineHelpText>
    <label>Skew Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Data_Skew_Result__c/fields/DSD_Skewed_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>DSD_Skewed_Record_ID__c</fullName>
    <description>The record id of the record that has data skew</description>
    <inlineHelpText>The record id of the record that has data skew</inlineHelpText>
    <label>Skewed Record ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Settings__c/DSD_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for the Data Skew Detector App</description>
    <label>Data Skew Detector Settings</label>
</CustomObject>

force-app/main/default/objects/DSD_Settings__c/fields/Child_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Object_API_Name__c</fullName>
    <description>The API name of the child object to look for data skew on</description>
    <inlineHelpText>The API name of the child object to look for data skew on</inlineHelpText>
    <label>Child Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSD_Settings__c/fields/Report_Other_Record_Counts__c.field-meta.xml
<CustomField>
    <fullName>Report_Other_Record_Counts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, record counts of child records will be recorded based on the Reportng Threshold value.</description>
    <inlineHelpText>When checked, record counts of child records will be recorded based on the Reportng Threshold value.</inlineHelpText>
    <label>Report Other Record Counts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSD_Settings__c/fields/Reporting_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged for reporting but not as having data skew</inlineHelpText>
    <label>Reporting Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSD_Settings__c/fields/Skew_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Skew_Threshold__c</fullName>
    <description>If a parent object has this many child records or more, it will be flagged as having data skew</description>
    <inlineHelpText>If a parent object has this many child records or more, it will be flagged as having data skew</inlineHelpText>
    <label>Skew Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DSD_TestOwnerDataSkewBatch.cls
@isTest
public with sharing class DSD_TestOwnerDataSkewBatch {
    
    @isTest
    static void TestLeadOwnershipWithSkew() {

        Integer skewThresholdForTest = 10;
        String childObject = 'Lead';
        Integer childObjectCount = 150;
        Integer childObjectCountWithoutSkew = 2;

        User u = DSD_TestSupport.getTestUser();
        System.assert(u != null);

        Lead[] leadsWithSkew = DSD_TestSupport.initTestLeads('dsd_testlead', childObjectCount);
        for(Lead l : leadsWithSkew) l.OwnerId = u.Id;
        insert leadsWithSkew;

        // add some leads not owned by this user to make sure they don't get counted in the skew count
        User u2 = DSD_TestSupport.initTestUser('mytestuser', 'testu');
        insert u2;
        Lead[] leadsWithoutSkew = DSD_TestSupport.initTestLeads('dsd_leadswithoutskew', childObjectCountWithoutSkew);
        for(Lead l : leadsWithoutSkew) l.OwnerId = u2.Id;
        insert leadsWithoutSkew;

        Test.startTest();
        DSD_Settings__c settings = DSD_SettingsSupport.getOwnerSettings();
        settings.Skew_Threshold__c = skewThresholdForTest;
        settings.Child_Object_API_Name__c = childObject;
        DSD_SettingsSupport.testOwnerSettings = settings;
        Database.executeBatch(new DSD_OwnerDataSkewBatch(childObject));
        Test.stopTest();

        DSD_Data_Skew_Result__c[] results = DSD_ResultsSupport.getResultsByType(DSD_SettingsSupport.SKEW_TYPE_OWNER);
        
        System.assertEquals(1, results.size());
        System.assertEquals(u.Id, results[0].DSD_Skewed_Record_ID__c);
        System.assertEquals(childObjectCount, results[0].DSD_Skew_Record_Count__c, 'Skew record count is incorrect');
        System.assertEquals('User', results[0].DSD_Parent_Object_API_Name__c, 'Parent object should be User but is not');
        System.assertEquals(childObject, results[0].DSD_Child_Object_API_Name__c, 'Child object should be Lead but is not');
    }

    @isTest
    static void TestLeadOwnershipWithoutSkew() {

        Integer skewThresholdForTest = 10000;
        String childObject = 'Lead';
        Integer childObjectCount = 150;
        
        User u = DSD_TestSupport.getTestUser();
        System.assert(u != null);

        Lead[] leadsWithSkew = DSD_TestSupport.initTestLeads('dsd_testlead', childObjectCount);
        for(Lead l : leadsWithSkew) l.OwnerId = u.Id;
        insert leadsWithSkew;

        Test.startTest();
        DSD_Settings__c settings = DSD_SettingsSupport.getOwnerSettings();
        settings.Skew_Threshold__c = skewThresholdForTest;
        settings.Child_Object_API_Name__c = childObject;
        DSD_SettingsSupport.testOwnerSettings = settings;
        Database.executeBatch(new DSD_OwnerDataSkewBatch(childObject));
        Test.stopTest();

        DSD_Data_Skew_Result__c[] results = DSD_ResultsSupport.getResultsByType(DSD_SettingsSupport.SKEW_TYPE_OWNER);
        System.assertEquals(0, results.size());
    }

    @isTest
    static void TestLeadOwnershipReportOtherCounts() {

        Integer skewThresholdForTest = 10000;
        Integer reportOtherThreshold = 10;
        String childObject = 'Lead';
        Integer childObjectCount = 150;
        
        User u = DSD_TestSupport.getTestUser();
        System.assert(u != null);

        Lead[] leadsWithSkew = DSD_TestSupport.initTestLeads('dsd_testlead', childObjectCount);
        for(Lead l : leadsWithSkew) l.OwnerId = u.Id;
        insert leadsWithSkew;

        Test.startTest();
        DSD_Settings__c settings = DSD_SettingsSupport.getOwnerSettings();
        settings.Skew_Threshold__c = skewThresholdForTest;
        settings.Child_Object_API_Name__c = childObject;
        settings.Report_Other_Record_Counts__c = true;
        settings.Reporting_Threshold__c = reportOtherThreshold;
        DSD_SettingsSupport.testOwnerSettings = settings;
        Database.executeBatch(new DSD_OwnerDataSkewBatch(childObject));
        Test.stopTest();

        DSD_Data_Skew_Result__c[] results = DSD_ResultsSupport.getResultsByType(DSD_SettingsSupport.SKEW_TYPE_OWNER);
        System.assertEquals(1, results.size());
        System.assertEquals(u.Id, results[0].DSD_Skewed_Record_ID__c);
        System.assertEquals(childObjectCount, results[0].DSD_Skew_Record_Count__c, 'Reported record count is incorrect');
        System.assertEquals('User', results[0].DSD_Parent_Object_API_Name__c, 'Parent object should be User but is not');
        System.assertEquals(childObject, results[0].DSD_Child_Object_API_Name__c, 'Child object should be Lead but is not');
    }
}